services:
  media-helper:
    container_name: media-helper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python -B main.py"
    env_file: "prod.env"
