services:
  media-helper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    environment:
      BOT_TOKEN: ""
      BOT_USERNAME: ""
      ALLOWED_USERNAMES: ""
